### PR TITLE
fix up dev dependencies. `npm install` actuall works now. Tests pass on Karma .12

### LINKED ISSUE #12: peer dependency conflict
when I try to checkout this package and run npm install, i get:

$ npm install .
npm ERR! peerinvalid The package karma does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-karma@0.6.2 wants karma@~0.10.0
npm ERR! peerinvalid Peer karma-mocha@0.1.4 wants karma@>=0.12.8

npm ERR! System Darwin 13.2.0
npm ERR! command "/usr/local/Cellar/node/0.10.25/bin/node" "/usr/local/bin/npm" "install" "."
npm ERR! cwd /Users/nick/git/karma-nodeunit
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/nick/git/karma-nodeunit/npm-debug.log
npm ERR! not ok code 0

I think the devDependencies need to be more restrictive...

### PR DESCRIPTION
**Pull request by nicks**
Fixes https://github.com/karma-runner/karma-nodeunit/issues/12

### CODE REVIEW

**Comment by aymericbeaumet** [comment]
Hey @nicks,

thanks for contributing.

Can you fix the Travis build? Also, please follow the [commit conventions](karma-runner.github.io/0.12/dev/git-commit-msg.html).

**Comment by nicks** [comment]
The commit message has been updated

There were 2 Travis CI failures: 

one was complaining b/c karma-firefox-launcher isn't packaged up with karma anymore, so i had to add that to devDependencies too.

The other one is complaining b/c someone upstream from you added a `^` semver dependency, and `^` does not exist in Node 0.8. To get Travis CI to pass, you would either need to drop support for Node 0.8, or drop the deps that are causing the problem (at least "grunt-contrib-jshint": "~0.7.x" is problematic, there may be others).

**Comment by aymericbeaumet** [comment]
Thanks for the update.

Concerning the remaining issue, I think `^` support is brought by a recent npm version, it is not related to node. Try to add the following line to `.travis.yml`:

```
before_install:
  - npm install -g npm
```

**Comment by nicks** [comment]
that worked! :dancer:

**Comment by hurrymaplelad** [comment]
Looks good.  Thanks @nicks

**Pull request merged**
